In [58]:
import pandas as pd
weather_data = {   # creating dataframe using python dictionary 
    'day': ['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'temperature': [32,35,28,24,32,31],
    'windspeed': [6,7,2,7,4,2],
    'event': ['Rain', 'Sunny', 'Snow','Snow','Rain', 'Sunny']
}
df = pd.DataFrame(weather_data)
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [4]:
df = pd.read_csv("weather_data.csv")
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [ ]:
df.shape # rows, columns

(6, 4)

In [6]:
df.head()

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

In [7]:
df.tail()

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [8]:
df[2:5]

        day  temperature  windspeed event
2  1/3/2017           28          2  Snow
3  1/4/2017           24          7  Snow
4  1/5/2017           32          4  Rain

In [9]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [11]:
df['temperature'] #df.temperature

0    32
1    35
2    28
3    24
4    32
5    31
Name: temperature, dtype: int64

In [ ]:
type(df.temperature)

pandas.core.series.Series

In [16]:
df[ ['day','temperature'] ]

        day  temperature
0  1/1/2017           32
1  1/2/2017           35
2  1/3/2017           28
3  1/4/2017           24
4  1/5/2017           32
5  1/6/2017           31

In [18]:
df.temperature.max() #int(df.temperature.max())

np.int64(35)

In [19]:
df.temperature.min()

np.int64(24)

In [20]:
df.temperature.mean()

np.float64(30.333333333333332)

In [21]:
df.temperature.std()

np.float64(3.8297084310253524)

In [22]:
df.temperature.var()

np.float64(14.666666666666666)

In [23]:
df.describe()

       temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

In [26]:
df[df.temperature > 32]

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

In [ ]:
df[df['temperature'] == df['temperature'].max()]

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

In [ ]:
df['day'][df['temperature'] >= 32]

0    1/1/2017
1    1/2/2017
4    1/5/2017
Name: day, dtype: object

In [36]:
df[['day','temperature']][df['temperature'] >= 32]

        day  temperature
0  1/1/2017           32
1  1/2/2017           35
4  1/5/2017           32

In [51]:
df.set_index('day', inplace=True)

In [52]:
df

          temperature  windspeed  event
day
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           31          2  Sunny

In [54]:
df.loc['1/3/2017']

temperature      28
windspeed         2
event          Snow
Name: 1/3/2017, dtype: object

In [55]:
df.reset_index(inplace=True)
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [59]:
df.set_index('event',inplace=True) 
df

            day  temperature  windspeed
event
Rain   1/1/2017           32          6
Sunny  1/2/2017           35          7
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7
Rain   1/5/2017           32          4
Sunny  1/6/2017           31          2

In [60]:
df.loc['Snow']

            day  temperature  windspeed
event
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7

In [61]:
df.reset_index(inplace=True)
df

   event       day  temperature  windspeed
0   Rain  1/1/2017           32          6
1  Sunny  1/2/2017           35          7
2   Snow  1/3/2017           28          2
3   Snow  1/4/2017           24          7
4   Rain  1/5/2017           32          4
5  Sunny  1/6/2017           31          2